export PATH=$PATH:/usr/local/bin:$HOME/git
# source files
source $HOME/.bash_basedir
BASHDOTDIR=$DOTFILESDIR/bash

source $BASHDOTDIR/bash_startup
source $BASHDOTDIR/bash_alias
source $BASHDOTDIR/bash_functions

# source bashrc if in Linux
if [ -f ~/.bashrc ]; then
  . ~/.bashrc
fi

# sourced to enable virtual environment up cd into directory
source /usr/local/opt/autoenv/activate.sh

function prompt
{
local WHITE="\[\033[1;37m\]"
local GREEN="\[\033[0;32m\]"
local CYAN="\[\033[0;36m\]"
local GRAY="\[\033[0;37m\]"
local BLUE="\[\033[0;34m\]"
local PURPLE="\[\033[0;35m\]"
local LIGHTPURPLE="\[\033[1;35m\]"
local BROWN="\[\033[0;33m\]"
local YELLOW="\[\033[1;33m\]"
local WHITE="\[\033[1;37m\]"
export PS1="
${GREEN}\u${CYAN}@${GRAY}\h ${CYAN}\w${WHITE}
$ "
}
prompt

#todo.txt specific items
export TODOTXT_DEFAULT_ACTION=ls
alias t='todo.sh -d $HOME/.todo/config'
source ~/git/dotfiles/todo.txt-cli/todo_completion
complete -F _todo t
#To use the mono assemblies from other formulae you need to set:
export MONO_GAC_PREFIX="/usr/local"


# enable powerline
function _update_ps1() {
    PS1="$($DOTFILESDIR/powerline-shell.py $? 2> /dev/null)"
}

if [ "$TERM" != "linux" ]; then
    PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
fi


# startup virtualenv-burrito
if [ -f $HOME/.venvburrito/startup.sh ]; then
    . $HOME/.venvburrito/startup.sh
fi

# autocompletion ignore case
bind "set completion-ignore-case on"
bind "set show-all-if-ambiguous on"

# Use vi editing mode
set editing-mode vi
set show-mode-in-prompt on
# set -o vi

# set defaults
export EDITOR=vim

# Tell ls to be colourful
export CLICOLOR=1
export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx
# Tell grep to highlight matches
export GREP_OPTIONS='--color=auto' colorize ls by default
export CLICOLOR=1


# OS specific actions
if [[ "$OSTYPE" == "linux-gnu" ]]; then
        # ...
	source $BASHDOTDIR/linuxSource

elif [[ "$OSTYPE" == "darwin"* ]]; then
    # Mac OSX
	source $BASHDOTDIR/macSource

#elif [[ "$OSTYPE" == "cygwin" ]]; then
        # POSIX compatibility layer and Linux environment emulation for Windows
#else
        # Unknown.
fi
